"""Add status column to transaction_summaries

Revision ID: 39a6c6767833
Revises: e03194aba4ed
Create Date: 2024-07-27 13:33:42.372183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39a6c6767833'
down_revision: Union[str, None] = 'e03194aba4ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_summaries', sa.Column('status', sa.Enum('PENDING', 'SUCCESSFUL', 'PARTIAL', name='transactionstatus'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('transaction_summaries', 'status')
    # ### end Alembic commands ###
