"""Add booking_payment_date to TransactionSummary

Revision ID: 6ecce63a9dc8
Revises: e5dfe22c12a6
Create Date: 2024-07-27 23:33:05.223327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ecce63a9dc8'
down_revision: Union[str, None] = 'e5dfe22c12a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_summaries', sa.Column('booking_payment_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_summaries', 'booking_payment_date')
    # ### end Alembic commands ###
