"""Add updated_by and updated_at to Transaction model

Revision ID: 8bdb3be8faf2
Revises: 6ecce63a9dc8
Create Date: 2024-07-29 20:20:59.549486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bdb3be8faf2'
down_revision: Union[str, None] = '6ecce63a9dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'updated_at')
    op.drop_column('transactions', 'updated_by')
    # ### end Alembic commands ###
